language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
branches:
  only:
  - master
before_install:
  - git clone https://github.com/cjpthree/genkey.git
  - cd genkey
  - mvn clean package
  - mvn install:install-file -Dfile=target/genkey-0.0.1-SNAPSHOT.jar.original

